---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
  namespace: ceph
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: ceph
    daemon: mon
spec:
  ports:
  - port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: ceph
    daemon: mon
  clusterIP: None
