apiVersion: v1
kind: Pod
metadata:
  labels:
    test: rbd
  name: ceph-rbd-test
  namespace: ceph
spec:
  nodeSelector:
    node-type: storage
  containers:
  - name: cephrbd-rw
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/cephrbd"
      name: cephrbd
  volumes:
  - name: cephrbd
    rbd:
      monitors:
#This only works if you have skyDNS resolveable from the kubernetes node. Otherwise you must manually put in one or more mon pod ips.
      - ceph-mon.ceph:6789
      user: admin
      image: ceph-rbd-test
      pool: rbd
      secretRef:
        name: ceph-client-key 
